'use client';
import { useEffect, useState } from 'react';
import { Search, Pencil, Settings, MessageCircle, Phone, Archive, MoreHorizontal, Video, PhoneCall, Smile, Plus, Send, ArrowLeft, Check, CheckCheck, Moon, LogOut, X } from 'lucide-react';
import { format, isToday, isYesterday } from 'date-fns';

type User={id:string;display_name:string;phone_number?:string;avatar_color:string;is_online:boolean;about?:string};
type Message={id:string;conversation_id:string;sender_id:string;sender?:User;body:string;created_at:string;client_message_id:string};
type Chat={id:string;type:string;title:string;participants:User[];last_message:Message|null;last_activity_at:string;unread_count:number;is_pinned:boolean;is_online:boolean;avatar_color:string};
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1';const WS=(process.env.NEXT_PUBLIC_WS_URL||'ws://localhost:8000/ws');
function initials(name:string){return name.split(' ').map(v=>v[0]).slice(0,2).join('').toUpperCase()}
function stamp(value:string){const d=new Date(value);return isToday(d)?format(d,'p'):isYesterday(d)?'Yesterday':format(d,'EEE')}
export default function Home(){
 const [token,setToken]=useState(''),[me,setMe]=useState<User|null>(null),[chats,setChats]=useState<Chat[]>([]),[selected,setSelected]=useState<Chat|null>(null),[messages,setMessages]=useState<Message[]>([]),[search,setSearch]=useState(''),[text,setText]=useState(''),[people,setPeople]=useState<User[]>([]),[modal,setModal]=useState(''),[phone,setPhone]=useState('+91 90000 00001'),[name,setName]=useState(''),[dark,setDark]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[connected,setConnected]=useState(false);
 async function request(path:string,init:RequestInit={}){const r=await fetch(API+path,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} :{}),...init.headers}});if(!r.ok)throw new Error((await r.json()).detail||'Request failed');return r.json()}
 useEffect(()=>{const saved=localStorage.getItem('signal-token');if(saved)setToken(saved)},[]);
 useEffect(()=>{if(!token)return;let active=true;request('/auth/me').then((u:User)=>{if(active)setMe(u)}).catch(()=>{localStorage.removeItem('signal-token');setToken('')});return()=>{active=false}},[token]);
 useEffect(()=>{if(!token||!me)return;let live=true;const refresh=()=>request('/conversations?q='+encodeURIComponent(search)).then((d:Chat[])=>{if(live){setChats(d);if(selected){const updated=d.find(c=>c.id===selected.id);if(updated)setSelected(updated)}}}).catch(()=>{});refresh();const timer=setInterval(refresh,5000);return()=>{live=false;clearInterval(timer)}},[token,me,search]);
 useEffect(()=>{if(!token||!me)return;const ws=new WebSocket(`${WS}?token=${encodeURIComponent(token)}`);ws.onopen=()=>setConnected(true);ws.onclose=()=>setConnected(false);ws.onmessage=(event)=>{const frame=JSON.parse(event.data);if(frame.type==='message.new'){const msg=frame.payload.message as Message;setChats(prev=>prev.map(c=>c.id===frame.payload.conversation_id?{...c,last_message:msg,last_activity_at:msg.created_at}:c).sort((a,b)=>b.last_activity_at.localeCompare(a.last_activity_at)));if(selected?.id===msg.conversation_id)setMessages(prev=>[...prev,msg])}if(frame.type==='message.ack')setMessages(prev=>prev.map(m=>m.client_message_id===frame.payload.client_message_id?{...m,id:frame.payload.message_id}:m))};return()=>ws.close()},[token,me,selected]);
 useEffect(()=>{if(!selected||!token)return;request(`/conversations/${selected.id}/messages`).then(setMessages).catch(()=>{});setMobileOpen(true)},[selected?.id,token]);
 async function login(){await request('/auth/request-otp',{method:'POST',body:JSON.stringify({identifier:phone})});const d=await request('/auth/verify-otp',{method:'POST',body:JSON.stringify({identifier:phone,code:'123456'})});localStorage.setItem('signal-token',d.token);setToken(d.token);setMe(d.user);if(d.is_new_user)setModal('profile')}
 async function saveProfile(){const u=await request('/auth/profile',{method:'PUT',body:JSON.stringify({display_name:name||'Signal User'})});setMe(u);setModal('')}
 async function openChat(chat:Chat){setSelected(chat);setMobileOpen(true)}
 async function newChat(person:User){const d=await request('/conversations/direct',{method:'POST',body:JSON.stringify({user_id:person.id})});const rows=await request('/conversations');setChats(rows);const c=rows.find((x:Chat)=>x.id===d.id);if(c)openChat(c);else setSelected({...d,title:person.display_name,participants:[person],last_message:null,last_activity_at:new Date().toISOString(),unread_count:0,is_pinned:false,is_online:person.is_online,avatar_color:person.avatar_color});setModal('')}
 async function send(){if(!text.trim()||!selected)return;const body=text.trim(),cid=selected.id,id=crypto.randomUUID();setText('');const optimistic:Message={id,conversation_id:cid,sender_id:me!.id,body,created_at:new Date().toISOString(),client_message_id:id};setMessages(v=>[...v,optimistic]);try{await request(`/conversations/${cid}/messages`,{method:'POST',body:JSON.stringify({body,client_message_id:id})})}catch{setMessages(v=>v.filter(m=>m.id!==id));setText(body)}}
 async function findPeople(){const result=await request('/users/search?q='+encodeURIComponent(search||'a'));setPeople(result);setModal('people')}
 if(!token||!me)return <main className="auth"><div className="auth-card"><div className="logo large">◉</div><h1>Welcome to Signal</h1><p>Say hello to a different messaging experience.</p><label>Phone number or username</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number"/><div className="hint">Use 123456 for verification</div><button className="primary wide" onClick={login}>Continue</button><small>By continuing, you agree to our Terms and Privacy Policy.</small></div></main>;
 return <main className={dark?'app dark':'app'}><aside className="rail"><div className="brand">◉</div><button className="rail-icon active" aria-label="Chats"><MessageCircle/></button><button className="rail-icon" onClick={()=>setModal('coming')} aria-label="Calls"><Phone/></button><div className="rail-spacer"/><button className="rail-icon" onClick={()=>setModal('settings')} aria-label="Settings"><Settings/></button><button className="mini-avatar" style={{background:me.avatar_color}} onClick={()=>setModal('settings')}>{initials(me.display_name)}</button></aside>
 <section className={`sidebar ${mobileOpen?'mobile-hidden':''}`}><header className="side-head"><button className="profile-chip" onClick={()=>setModal('settings')}><div className="avatar tiny" style={{background:me.avatar_color}}>{initials(me.display_name)}</div><span>{me.display_name}</span></button><button className="icon-button" onClick={()=>setModal('compose')} aria-label="New message"><Pencil size={19}/></button></header><div className="search-wrap"><Search size={17}/><input placeholder="Search" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button onClick={()=>setSearch('')}><X size={15}/></button>}</div><div className="section-label">MESSAGES</div><div className="chat-list">{chats.map(c=><button key={c.id} className={`chat-item ${selected?.id===c.id?'selected':''}`} onClick={()=>openChat(c)}><div className="avatar" style={{background:c.avatar_color}}>{initials(c.title||'Group')}{c.is_online&&<i className="online-dot"/>}</div><div className="chat-meta"><div className="chat-first"><strong>{c.title}</strong><time>{c.last_message?stamp(c.last_message.created_at):''}</time></div><div className="chat-second"><span>{c.last_message?.sender_id===me.id?'You: ':''}{c.last_message?.body||'No messages yet'}</span>{c.unread_count>0&&<b className="unread">{c.unread_count}</b>}</div></div></button>)}{!chats.length&&<div className="list-empty">No conversations yet.<br/><button onClick={()=>setModal('compose')}>Start a conversation</button></div>}</div><footer className="side-footer"><span className={connected?'status-dot':'status-dot offline'}/>{connected?'Signal is connected':'Connecting…'}</footer></section>
 <section className={`conversation ${mobileOpen?'mobile-visible':''}`}>{selected?<><header className="chat-header"><button className="back-button" onClick={()=>setMobileOpen(false)}><ArrowLeft/></button><div className="avatar small" style={{background:selected.avatar_color}}>{initials(selected.title)}</div><div className="head-info"><strong>{selected.title}</strong><span>{selected.is_online?'online':selected.type==='group'?`${selected.participants?.length||0} members`:'last seen recently'}</span></div><div className="head-actions"><button aria-label="Voice call" onClick={()=>setModal('coming')}><PhoneCall/></button><button aria-label="Video call" onClick={()=>setModal('coming')}><Video/></button><button aria-label="More" onClick={()=>setModal('chat-menu')}><MoreHorizontal/></button></div></header><div className="encryption"><span>◈</span> Messages are end-to-end encrypted <button onClick={()=>setModal('encryption')}>Learn more</button></div><div className="messages" id="messages">{messages.map((m,i)=>{const own=m.sender_id===me.id;return <div key={m.id} className={`message-row ${own?'own':''}`}><div className={`bubble ${own?'outgoing':''}`}><div>{m.body}</div><div className="bubble-meta"><time>{format(new Date(m.created_at),'p')}</time>{own&&<Check size={13}/>}</div></div></div>})}</div><div className="composer"><button className="compose-icon" onClick={()=>setModal('coming')} aria-label="Attach"><Plus/></button><button className="compose-icon" aria-label="Emoji" onClick={()=>setText(text+'🙂')}><Smile/></button><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Write a message…" rows={1}/>{text.trim()?<button className="send-button" onClick={send} aria-label="Send"><Send size={18}/></button>:<span className="composer-lock">▣</span>}</div></>:<div className="welcome-pane"><div className="welcome-mark">◉</div><h2>Select a chat to start messaging</h2><p>Send a message to anyone securely.</p><button className="primary" onClick={()=>setModal('compose')}>New message</button></div>}</section>
 {modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setModal('')}}><div className="modal"><button className="modal-close" onClick={()=>setModal('')}><X size={19}/></button>{modal==='compose'?<><h2>New message</h2><p>Choose someone to start a conversation.</p><div className="modal-search"><Search size={17}/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name or number"/><button onClick={findPeople}>Search</button></div><button className="person-row" onClick={findPeople}><div className="avatar small">+</div><span>Find people</span></button></>:modal==='people'?<><h2>People</h2>{people.map(p=><button className="person-row" key={p.id} onClick={()=>newChat(p)}><div className="avatar small" style={{background:p.avatar_color}}>{initials(p.display_name)}</div><span>{p.display_name}</span></button>)}</>:modal==='settings'?<><h2>Settings</h2><div className="settings-profile"><div className="avatar" style={{background:me.avatar_color}}>{initials(me.display_name)}</div><div><b>{me.display_name}</b><small>{me.phone_number}</small></div></div><button className="setting-row" onClick={()=>setDark(!dark)}><Moon size={18}/> Appearance <span>{dark?'Dark':'Light'}</span></button><button className="setting-row" onClick={()=>setModal('coming')}>Privacy <span>›</span></button><button className="setting-row" onClick={()=>setModal('coming')}>Notifications <span>›</span></button><button className="setting-row danger" onClick={()=>{localStorage.removeItem('signal-token');setToken('');setMe(null)}}><LogOut size={18}/> Sign out</button></>:modal==='profile'?<><h2>Set up your profile</h2><p>How should people see you?</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/><button className="primary wide" onClick={saveProfile}>Continue</button></>:<><h2>{modal==='encryption'?'End-to-end encrypted':modal==='chat-menu'?'Conversation options':'Coming soon'}</h2><p>{modal==='encryption'?'Your personal messages are private and only visible to the people in this conversation.':'This feature will be available in a future update.'}</p><button className="primary wide" onClick={()=>setModal('')}>Got it</button></>}</div></div>}
 </main>
}
