'use client';
import { useEffect, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { ArrowLeft, Phone, Video, MoreVertical, Search, Send, Smile, Paperclip, ShieldCheck } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { format } from 'date-fns';
import { conversationApi, messageApi, uploadApi } from '@/lib/chatApi';
import { useWebSocket } from '@/hooks/useWebSocket';
import { useMessages } from '@/hooks/useMessages';
import { useTyping } from '@/hooks/useTyping';
import { useChatStore } from '@/store/chatStore';
import { useUiStore } from '@/store/uiStore';
import { usePresenceStore } from '@/store/presenceStore';
import { Avatar } from '@/components/ui/Avatar';

export function ChatView(){
 const {conversationId}=useParams<{conversationId:string}>();const router=useRouter();const sendEvent=useWebSocket();const {data:conversation}=useQuery({queryKey:['conversation',conversationId],queryFn:()=>conversationApi.details(conversationId)});const {messages,loading,sendMessage,loadPrevious,hasPrevious}=useMessages(conversationId,sendEvent);const typingIds=useChatStore(s=>s.typingByConversation[conversationId]??[]);const presence=usePresenceStore(s=>s.onlineUserIds);const [draft,setDraft]=useState('');const [reply,setReply]=useState<string|null>(null);const bottom=useRef<HTMLDivElement>(null);const scroll=useRef<HTMLDivElement>(null);const typing=useTyping(sendEvent,conversationId);
 useEffect(()=>{if(scroll.current&&scroll.current.scrollHeight-scroll.current.scrollTop-scroll.current.clientHeight<180)bottom.current?.scrollIntoView({behavior:'smooth'});},[messages.length]);
 if(!conversation)return <div className="loading-screen">Loading conversation…</div>;const peer=conversation.participants[0];const title=conversation.title||peer?.display_name||'Conversation';
 function submit(){if(!draft.trim())return;sendMessage(draft.trim(),reply??undefined);setDraft('');setReply(null);typing('');}
 return <section className="chat-view"><header className="chat-header"><button className="icon-button mobile-back" onClick={()=>router.push('/')} aria-label="Back"><ArrowLeft/></button><Avatar name={title} color={conversation.avatar_color} imageUrl={peer?.avatar_url} online={peer?presence[peer.id]??conversation.is_online:false}/><div className="chat-heading"><b>{title}</b><small>{conversation.type==='group'?`${conversation.participants.length} members`:peer&&(presence[peer.id]??conversation.is_online)?'online':peer?.last_seen_at?`last seen ${format(new Date(peer.last_seen_at),'MMM d, h:mm a')}`:'offline'}</small></div><button className="icon-button" aria-label="Voice call" onClick={()=>useUiStore.getState().notify('Voice calls are coming soon.')}><Phone/></button><button className="icon-button" aria-label="Video call" onClick={()=>useUiStore.getState().notify('Video calls are coming soon.')}><Video/></button><button className="icon-button" aria-label="Search messages"><Search/></button><button className="icon-button" aria-label="More options" onClick={()=>useUiStore.getState().openModal('conversation-info')}><MoreVertical/></button></header>
 <div className="encryption-banner"><ShieldCheck size={14}/> Messages are end-to-end encrypted <button onClick={()=>useUiStore.getState().notify('Safety number verification is a demo placeholder.')}>Learn more</button></div>
 <div className="message-list" ref={scroll} onScroll={e=>{if(e.currentTarget.scrollTop===0&&hasPrevious)void loadPrevious();}}>{loading&&<p className="inline-loading">Loading messages…</p>}{messages.map((message,index)=>{const prior=messages[index-1];const grouped=prior?.sender_id===message.sender_id&&new Date(message.created_at).getTime()-new Date(prior.created_at).getTime()<300000;const fresh=!prior||new Date(prior.created_at).toDateString()!==new Date(message.created_at).toDateString();return <div key={message.id}>{fresh&&<div className="date-divider"><span>{format(new Date(message.created_at),'MMMM d, yyyy')}</span></div>}{message.type==='system'?<div className="system-message">{message.body}</div>:<article className={`message-row ${message.sender_id===peer?.id?'incoming':'outgoing'} ${grouped?'grouped':''}`}><div className="bubble"><div>{message.body}</div>{message.attachments.map(a=><a key={a.id} href={a.url} target="_blank" rel="noreferrer">📎 {a.file_name}</a>)}<footer><time>{format(new Date(message.created_at),'h:mm a')}</time>{message.sender_id!==peer?.id&&<span className={`ticks ${message.status==='read'?'read':''}`}>{message.status==='sending'?'◷':message.status==='sent'?'✓':'✓✓'}</span>}</footer></div><button className="reply-action" onClick={()=>setReply(message.id)}>↩</button><button className="reaction-action" onClick={()=>void messageApi.react(message.id,'❤️')}>♡</button>{message.reactions?.map(r=><span className="reaction-chip" key={r.emoji}>{r.emoji} {r.count}</span>)}</article>}</div>})}{typingIds.length>0&&<div className="typing-indicator"><i/><i/><i/> typing</div>}<div ref={bottom}/></div>
 <div className="composer-wrap">{reply&&<div className="reply-preview"><span>Replying to message</span><button onClick={()=>setReply(null)}>×</button></div>}<div className="composer"><button className="icon-button" aria-label="Emoji" onClick={()=>setDraft(d=>`${d} 🙂`)}><Smile/></button><textarea value={draft} placeholder="Write a message…" rows={1} onChange={e=>{setDraft(e.target.value);typing(e.target.value)}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}}}/><label className="icon-button attach-button" aria-label="Attach file"><Paperclip/><input type="file" hidden onChange={async e=>{const file=e.target.files?.[0];if(file){try{const a=await uploadApi.upload(file);sendMessage('',undefined,[a.id]);}catch{useUiStore.getState().notify('Upload failed.')}}}}/></label><button className="send-button" aria-label="Send" onClick={submit} disabled={!draft.trim()}><Send size={18}/></button></div></div></section>
}
